[package]
name = "place_me"
version = "0.1.0"
edition = "2018"

[lib]
name = "place_me"
crate-type = ["cdylib"]


[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
rayon = "1.0.3"
numpy = "0.20.0"

[profile.release]
lto = "fat"
codegen-units = 1
